# Generated by Django 2.2.14 on 2021-09-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201209_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('gallerya', models.ImageField(blank=True, null=True, upload_to='')),
                ('galleryb', models.ImageField(blank=True, null=True, upload_to='')),
                ('galleryc', models.ImageField(blank=True, null=True, upload_to='')),
                ('galleryd', models.ImageField(blank=True, null=True, upload_to='')),
                ('gallerye', models.ImageField(blank=True, null=True, upload_to='')),
                ('galleryf', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='apartment_address',
            field=models.CharField(default='4 Aromire Avenue, Ikeja', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='08156912548', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(default='Aromire Avenue, Ikeja', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('song', 'song'), ('beat', 'beat'), ('book', 'book'), ('art', 'art'), ('digital_product', 'digital_product')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('audio', 'audio'), ('video', 'video'), ('pdf', 'pdf'), ('art', 'art')], max_length=20),
        ),
    ]
