# Generated by Django 2.2.14 on 2021-09-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210908_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default='Aromire Avenue, Ikeja', max_length=200),
        ),
    ]
