# Generated by Django 2.2.14 on 2021-09-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210909_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemfile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
